# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='\u7bb1\u53f7')),
                ('type', models.CharField(blank=True, default='40HQ', max_length=30, null=True, verbose_name='\u7bb1\u578b')),
                ('usage', models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='\u4f7f\u7528\u6b21\u6570')),
                ('reference', models.CharField(blank=True, max_length=30, null=True, verbose_name='reference')),
                ('enterDate', models.DateField(blank=True, null=True, verbose_name='\u8fdb\u573a\u65e5')),
                ('roll_outDate', models.DateField(blank=True, null=True, verbose_name='\u8f6c\u51fa\u5806\u573a\u65e5')),
                ('damageCondition', models.CharField(blank=True, default='\u826f\u597d', max_length=30, null=True, verbose_name='\u635f\u574f\u60c5\u51b5')),
            ],
        ),
    ]
